import type { Club, Member, Meeting, Document, Competition, ActivityLog, Alert } from './types';

export const club: Club = {
  id: 'club-1',
  name: 'Karate klub Rijeka',
  shortName: 'KK Rijeka',
  oib: '12345678901',
  address: 'Korzo 14',
  city: 'Rijeka',
  founded: 1987,
  presidentName: 'Ante Marković',
  presidentMandateExpiry: '2026-07-15',
  secretaryName: 'Maja Horvat',
  email: 'info@kk-rijeka.hr',
  phone: '+385 51 123 456',
  memberCount: 87,
};

export const members: Member[] = [
  {
    id: 'm-1',
    firstName: 'Luka',
    lastName: 'Perić',
    email: 'luka.peric@gmail.com',
    phone: '+385 91 234 5678',
    birthDate: '2005-03-14',
    memberSince: '2018-09-01',
    belt: 'crni-1',
    status: 'aktivan',
    medicalExpiry: '2026-06-30',
    consentSigned: true,
    category: 'junior',
  },
  {
    id: 'm-2',
    firstName: 'Ana',
    lastName: 'Kovač',
    email: 'ana.kovac@gmail.com',
    phone: '+385 98 765 4321',
    birthDate: '2010-07-22',
    memberSince: '2020-01-15',
    belt: 'zeleni',
    status: 'aktivan',
    medicalExpiry: '2027-01-10',
    consentSigned: true,
    guardian: 'Ivana Kovač',
    category: 'kadet',
  },
  {
    id: 'm-3',
    firstName: 'Marko',
    lastName: 'Babić',
    email: 'marko.babic@email.hr',
    phone: '+385 92 111 2222',
    birthDate: '1998-11-05',
    memberSince: '2015-09-01',
    belt: 'crni-2',
    status: 'aktivan',
    medicalExpiry: '2025-12-15',
    consentSigned: true,
    category: 'senior',
  },
  {
    id: 'm-4',
    firstName: 'Petra',
    lastName: 'Jurić',
    email: 'petra.juric@gmail.com',
    phone: '+385 95 333 4444',
    birthDate: '2012-04-18',
    memberSince: '2021-09-01',
    belt: 'žuti',
    status: 'aktivan',
    medicalExpiry: '2026-09-20',
    consentSigned: false,
    guardian: 'Tomislav Jurić',
    category: 'mali_karatist',
  },
  {
    id: 'm-5',
    firstName: 'Ivan',
    lastName: 'Novak',
    email: 'ivan.novak@email.hr',
    phone: '+385 99 555 6666',
    birthDate: '1995-08-30',
    memberSince: '2012-09-01',
    belt: 'smeđi',
    status: 'neaktivan',
    medicalExpiry: '2025-03-01',
    consentSigned: true,
    category: 'senior',
  },
  {
    id: 'm-6',
    firstName: 'Sara',
    lastName: 'Tomić',
    email: 'sara.tomic@gmail.com',
    phone: '+385 91 777 8888',
    birthDate: '2008-12-03',
    memberSince: '2019-09-01',
    belt: 'plavi',
    status: 'aktivan',
    medicalExpiry: '2026-04-05',
    consentSigned: true,
    guardian: 'Drago Tomić',
    category: 'kadet',
  },
  {
    id: 'm-7',
    firstName: 'Tomislav',
    lastName: 'Krstić',
    email: 'tomislav.krstic@email.hr',
    phone: '+385 98 999 0000',
    birthDate: '1985-05-15',
    memberSince: '2008-03-01',
    belt: 'crni-3',
    status: 'aktivan',
    medicalExpiry: '2026-11-30',
    consentSigned: true,
    category: 'veteran',
  },
];

export const meetings: Meeting[] = [
  {
    id: 'meet-1',
    type: 'redovna',
    date: '2026-06-15',
    time: '18:00',
    location: 'Sportska dvorana Kantrida, Rijeka',
    agenda: [
      'Otvaranje skupštine i provjera kvoruma',
      'Usvajanje dnevnog reda',
      'Izvješće predsjednika o radu kluba',
      'Financijsko izvješće za 2024. godinu',
      'Plan aktivnosti za 2025. godinu',
      'Razno',
    ],
    status: 'planirana',
    attendees: [],
    documents: [],
  },
  {
    id: 'meet-2',
    type: 'redovna',
    date: '2024-12-10',
    time: '19:00',
    location: 'Sportska dvorana Kantrida, Rijeka',
    agenda: [
      'Pregled aktivnosti u 2024. godini',
      'Financijsko izvješće',
      'Planovi za 2025.',
    ],
    status: 'završena',
    attendees: ['m-1', 'm-3', 'm-7'],
    notes: 'Skupština je uspješno održana. Usvojeni su svi dokumenti.',
    documents: [
      {
        id: 'doc-1',
        meetingId: 'meet-2',
        type: 'zapisnik',
        title: 'Zapisnik s redovne skupštine — 10.12.2024.',
        status: 'usvojeno',
        createdAt: '2024-12-10T21:00:00Z',
        content: 'Skupština je otvorena u 19:00 sati...',
        author: 'Maja Horvat',
      },
    ],
  },
];

export const competitions: Competition[] = [
  {
    id: 'comp-1',
    name: 'Međunarodna karate liga — Zagreb Open 2025',
    date: '2025-05-18',
    location: 'Sportska dvorana Zagreb',
    type: 'oboje',
    level: 'međunarodno',
    results: [
      {
        memberId: 'm-1',
        memberName: 'Luka Perić',
        category: 'Junior muški do 68 kg',
        place: 1,
        medal: 'zlato',
        event: 'Kumite',
      },
      {
        memberId: 'm-6',
        memberName: 'Sara Tomić',
        category: 'Kadet ženski kata',
        place: 2,
        medal: 'srebro',
        event: 'Kata',
      },
      {
        memberId: 'm-2',
        memberName: 'Ana Kovač',
        category: 'Kadet ženski do 47 kg',
        place: 3,
        medal: 'bronca',
        event: 'Kumite',
      },
    ],
  },
];

export const activityLog: ActivityLog[] = [
  {
    id: 'act-1',
    userId: 'user-1',
    userName: 'Maja Horvat',
    action: 'dodao/la novog člana',
    entity: 'Član',
    entityId: 'm-2',
    timestamp: '2025-05-27T09:15:00Z',
    icon: 'UserPlus',
  },
  {
    id: 'act-2',
    userId: 'user-1',
    userName: 'Maja Horvat',
    action: 'generirala AI izvještaj za natjecanje',
    entity: 'Natjecanje',
    entityId: 'comp-1',
    timestamp: '2025-05-26T14:30:00Z',
    icon: 'Sparkles',
  },
  {
    id: 'act-3',
    userId: 'user-2',
    userName: 'Ante Marković',
    action: 'zakazao skupštinu',
    entity: 'Skupština',
    entityId: 'meet-1',
    timestamp: '2025-05-25T11:00:00Z',
    icon: 'Calendar',
  },
  {
    id: 'act-4',
    userId: 'user-1',
    userName: 'Maja Horvat',
    action: 'ažurirala liječnički pregled',
    entity: 'Član',
    entityId: 'm-7',
    timestamp: '2025-05-24T16:45:00Z',
    icon: 'Heart',
  },
  {
    id: 'act-5',
    userId: 'user-2',
    userName: 'Ante Marković',
    action: 'usvojio dokument',
    entity: 'Dokument',
    entityId: 'doc-1',
    timestamp: '2025-05-23T10:20:00Z',
    icon: 'CheckCircle',
  },
];

export const alerts: Alert[] = [
  {
    id: 'alert-1',
    type: 'critical',
    title: 'Istek mandata predsjednika',
    description: 'Mandat predsjednika Ante Markovića ističe za 49 dana (15.07.2026.).',
    action: 'Zakaži skupštinu',
    actionUrl: '/skupstine',
  },
  {
    id: 'alert-2',
    type: 'warning',
    title: 'Istekli liječnički pregledi',
    description: '3 člana imaju istekle liječničke preglede i ne mogu natjecati.',
    action: 'Pregledaj članove',
    actionUrl: '/clanovi',
    count: 3,
  },
  {
    id: 'alert-3',
    type: 'warning',
    title: 'Nepotpisane privole',
    description: '1 maloljetni član nema potpisanu privolu roditelja.',
    action: 'Pregledaj',
    actionUrl: '/clanovi',
    count: 1,
  },
  {
    id: 'alert-4',
    type: 'info',
    title: 'Skupština zakazana',
    description: 'Redovna skupština zakazana je za 15.06.2026. u 18:00h.',
    action: 'Detalji',
    actionUrl: '/skupstine',
  },
];

export const beltLabels: Record<string, { label: string; color: string; bg: string }> = {
  bijeli:    { label: 'Bijeli pojas',   color: 'text-slate-300', bg: 'bg-slate-700' },
  žuti:      { label: 'Žuti pojas',     color: 'text-yellow-300', bg: 'bg-yellow-900/40' },
  narančasti:{ label: 'Narančasti',     color: 'text-orange-300', bg: 'bg-orange-900/40' },
  zeleni:    { label: 'Zeleni pojas',   color: 'text-green-300',  bg: 'bg-green-900/40' },
  plavi:     { label: 'Plavi pojas',    color: 'text-blue-300',   bg: 'bg-blue-900/40' },
  smeđi:     { label: 'Smeđi pojas',   color: 'text-amber-600',  bg: 'bg-amber-900/40' },
  'crni-1':  { label: '1. Dan',         color: 'text-slate-100',  bg: 'bg-slate-900 border border-slate-600' },
  'crni-2':  { label: '2. Dan',         color: 'text-slate-100',  bg: 'bg-slate-900 border border-slate-500' },
  'crni-3':  { label: '3. Dan',         color: 'text-yellow-300', bg: 'bg-slate-900 border border-yellow-500' },
};
